<?php

use yii\db\Migration;

/**
 * Handles the creation for table `user`.
 */
class m160622_103521_create_user extends Migration
{
    public function createTable($table, $columns, $options = null)
    {
        if (!$options) {
            $options = 'CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE=InnoDB';
        }

        parent::createTable($table, $columns, $options); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function up()
    {
        $this->createTable('{{%user}}', [
            'id' => $this->string(36)->notNull(),
            'username' => $this->string(200)->notNull()->unique(),
            'password_hash' => $this->string(60),
            'auth_key' => $this->string(36),
        ]);

        $this->addPrimaryKey('pk_user', '{{%user}}', 'id');
    }

    /**
     * @inheritdoc
     */
    public function down()
    {
        $this->dropTable('{{%user}}');
    }
}
